# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QueryAwsLogs < Formula
  desc "A tool helping you to explore logs in AWS CloudWatch Logs"
  homepage "https://github.com/bananaumai/query-aws-logs"
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bananaumai/query-aws-logs/releases/download/v0.0.5/query-aws-logs_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "fe4808b4697341a23625b627beb772eaf9c8278af743c26cfb23d8ccb4be2b77"
    end
    if Hardware::CPU.arm?
      url "https://github.com/bananaumai/query-aws-logs/releases/download/v0.0.5/query-aws-logs_0.0.5_Darwin_arm64.tar.gz"
      sha256 "edf1e32b490fa6781c2f961b9298db6299f9820eccdf2c7b140fef97ede37fd6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bananaumai/query-aws-logs/releases/download/v0.0.5/query-aws-logs_0.0.5_Linux_x86_64.tar.gz"
      sha256 "4f887217adff27e56093f1e9328f3ede141d328934fad89866ee0fb85a8bd940"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bananaumai/query-aws-logs/releases/download/v0.0.5/query-aws-logs_0.0.5_Linux_arm64.tar.gz"
      sha256 "ad67730dc6ca651f5d894c6c21670e49d47a4e04ecd1bd251243411eb31939ef"
    end
  end

  def install
    bin.install "query-aws-logs"
  end
end
